import { expect, test } from './fixtures.ts'
import { seedIntake } from './helpers.ts'

test('ux shots', async ({ page }, info) => {
  test.skip(info.project.name !== 'iphone')
  const dir = process.env.SHOTS ?? 'ux1'
  const shoot = async (name: string) => {
    await page.evaluate(() => document.fonts.ready)
    await page.waitForTimeout(400)
    await page.screenshot({ path: `docs/screens/${dir}/${name}.png` })
  }
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await seedIntake(page)
  await page.waitForTimeout(1500)
  await shoot('today')
  await page.goto('./#/session')
  await expect(page.getByText(/игра «Помехи»/)).toBeVisible()
  await shoot('plan')
  await page.goto('./#/tracks')
  await page.waitForTimeout(500)
  await shoot('course')
  await page.getByText('Все модули (8)').first().click()
  await shoot('course-open')
  await page.goto('./#/more')
  await shoot('training')
  await page.goto('./#/me')
  await shoot('me')
  await page.goto('./#/dictionary')
  await shoot('dictionary')
  await page.goto('./#/run/seg/air-1')
  await page.getByRole('button', { name: 'Понятно, поехали' }).click()
  await page.getByRole('group', { name: 'Что прозвучало?' }).waitFor()
  await shoot('listen')
  await page.getByRole('group', { name: 'Что прозвучало?' }).getByRole('button').nth(1).click()
  await shoot('listen-answer')
  await page.goto('./#/game/static?seg=warmup&seconds=3')
  await page.getByRole('button', { name: 'Старт' }).click()
  await expect(page.getByRole('heading', { name: 'Раунд окончен' })).toBeVisible({ timeout: 15_000 })
  await shoot('between-blocks')
})
